apiVersion: v1
kind: Service
metadata:
  name: payroll-service
  namespace: andikisha
  labels:
    app: payroll-service
    app.kubernetes.io/name: payroll-service
    app.kubernetes.io/part-of: andikisha-hr
spec:
  type: ClusterIP
  selector:
    app: payroll-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
    - name: grpc
      port: 9084
      targetPort: 9084
      protocol: TCP
