spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  rabbitmq:
    listener:
      simple:
        auto-startup: false

app:
  mpesa:
    enabled: false

grpc:
  server:
    port: 0