apiVersion: v1
kind: ConfigMap
metadata:
  name: andikisha-config
  namespace: andikisha
data:
  rabbitmq-host: "rabbitmq"
  redis-host: "redis"
  zipkin-endpoint: "http://zipkin:9411/api/v2/spans"
  auth-db-host: "auth-postgres"
  tenant-db-host: "tenant-postgres"
  employee-db-host: "employee-postgres"
  payroll-db-host: "payroll-postgres"
  compliance-db-host: "compliance-postgres"
  leave-db-host: "leave-postgres"
  attendance-db-host: "attendance-postgres"
  document-db-host: "document-postgres"
  notification-db-host: "notification-postgres"
  integration-db-host: "integration-postgres"
  analytics-db-host: "analytics-postgres"
  audit-db-host: "audit-postgres"
