apiVersion: v1
kind: ConfigMap
metadata:
  name: andikisha-config
  namespace: andikisha
data:
  rabbitmq-host: "b-2acd1a9e-cb43-4900-938b-d2ea5fb96c57.mq.af-south-1.on.aws"
  redis-host: "andikishahr-andikishahr.4tz6iw.0001.afs1.cache.amazonaws.com"
  zipkin-endpoint: "http://zipkin:9411/api/v2/spans"
  auth-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  tenant-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  employee-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  payroll-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  compliance-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  leave-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  attendance-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  document-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  notification-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  integration-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  analytics-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
  audit-db-host: "andikishahr-andikishahr.ctkya2cgi5u7.af-south-1.rds.amazonaws.com"
