apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - ../services/api-gateway
  - ../services/auth-service
  - ../services/tenant-service
  - ../services/employee-service
  - ../services/payroll-service
  - ../services/compliance-service
  - ../services/time-attendance-service
  - ../services/leave-service
  - ../services/document-service
  - ../services/notification-service
  - ../services/integration-hub-service
  - ../services/analytics-service
  - ../services/audit-service
