apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: andikisha
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: andikisha-hr
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: grpc
      port: 9081
      targetPort: 9081
      protocol: TCP
