apiVersion: v1
kind: Service
metadata:
  name: time-attendance-service
  namespace: andikisha
  labels:
    app: time-attendance-service
    app.kubernetes.io/name: time-attendance-service
    app.kubernetes.io/part-of: andikisha-hr
spec:
  type: ClusterIP
  selector:
    app: time-attendance-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
    - name: grpc
      port: 9086
      targetPort: 9086
      protocol: TCP
