ALTER TABLE role_permissions
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN version    BIGINT    NOT NULL DEFAULT 0;
