apiVersion: v1
kind: Service
metadata:
  name: leave-service
  namespace: andikisha
  labels:
    app: leave-service
    app.kubernetes.io/name: leave-service
    app.kubernetes.io/part-of: andikisha-hr
spec:
  type: ClusterIP
  selector:
    app: leave-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087
      protocol: TCP
    - name: grpc
      port: 9087
      targetPort: 9087
      protocol: TCP
