apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: andikisha
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: andikisha-hr
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8089
      targetPort: 8089
      protocol: TCP
    - name: grpc
      port: 9089
      targetPort: 9089
      protocol: TCP
